### ISSUE TITLE
Improve navbar menu in mobile view.

### ISSUE THREAD

**Issue by SubhamB2003** [Eduhub-Community/Eduhub-Community.github.io#137]
@SahityaRoy  Hey, The navbar menu in mobile view is not looking good and the text is not showing well.

![image](https://user-images.githubusercontent.com/94003231/215659691-12551217-438a-42c6-8644-2bb5d8461919.png)

After improvement

![image](https://user-images.githubusercontent.com/94003231/215660178-5268ef74-e102-4459-b0b3-266d92f0ee29.png)

Please assign it to me under GSSOC 23. I would love to work on it.

**Comment by Chirag-04** [comment]
@SubhamB2003 Hope you're doing well! I'm eager to work on this task and would greatly appreciate it if you could assign it to me.

**Comment by SamridhiNancy** [comment]
"Hi there! I'm excited to contribute to this project'GSSOC;'23 I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by SubhamB2003** [comment]
> @SubhamB2003 Hope you're doing well! I'm eager to work on this task and would greatly appreciate it if you could assign it to me.

Hello @Chirag-04 I am not the owner of this repo. Only the owner can assign you this.

**Comment by SahityaRoy** [comment]
@SubhamB2003 go ahead.

**Comment by SubhamB2003** [comment]
> @SubhamB2003 go ahead.

Hey, I am not able to clone this repo. It always shows me this error

![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/94003231/b7722edd-01b4-4c21-9ea1-e73fd1da9377)

Can you please give me some suggestions on how can I fix this
