### ISSUE TITLE
Broken Link

### ISSUE THREAD

**Issue by Bharadwajshivam28** [Eduhub-Community/Eduhub-Community.github.io#142]
In the footer section the ig link is broken

Dropping the ss- 

![Screenshot from 2023-05-20 00-27-37](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/108119109/b9756fe5-aaa4-46a9-916b-d523b05d718e)

Please assign me under GSSOC23

**Comment by Aditi323** [comment]
I would like to work on this project. Please assign it to me.
