### ISSUE TITLE
Home page ' --> ' comment mark is visible on the screen and Mid Content 

### ISSUE THREAD

**Issue by SyedImtiyaz-1** [Eduhub-Community/Eduhub-Community.github.io#144]
Hello,
As you can see the **Images** there is a problem with the **Home page** regarding the comment mark also with the mid content.

### Major Issue -
**Why major issue**
I'hv seen that every content in the website is proper but when I looked at the below 1st img (you can see the img below) then I check the responsiveness and thought every element is in the middle but why this is not performing well it's really too close to the edges.
### I'm Working on this issue soon raise a PR.

![Screenshot from 2023-05-20 01-25-32](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/121503426/aa03837a-00fc-4680-9b34-316b7b249770)

### Basic Issue -
See this was a bit mistake I think which had done while adding comment.
![Screenshot from 2023-05-20 01-16-40](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/121503426/5423634c-2147-4faa-b220-4aad60f0e734)

**Comment by anuza08** [comment]
hey, can you assign me this issue??
