### ISSUE TITLE
Improving the readme file 

### ISSUE THREAD

**Issue by harshsingh32** [Eduhub-Community/Eduhub-Community.github.io#158]
I would like to work to improve the readme file of this project making it engaging for the users and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue, please assign this issue to me under GSSoC'23.

**Comment by SamridhiNancy** [comment]
@Athi223
"Hi there! I'm excited to contribute to this project for GSSOC'23'. I've taken a look at the codebase and I believe I can make some valuable improvements. I'll start working on it right away. If you have any specific requirements or suggestions, please let me know. Looking forward to collaborating with you all on this!

**Comment by divyanshiet** [comment]
hello @Athi223  I would like to contribute in this project and under this issue for GSSOC'23. the current one was good but adding some badges among this will make it more attractive kindly assign it to me.
