### ISSUE TITLE
Improving the index.html file

### ISSUE THREAD

**Issue by harshsingh32** [Eduhub-Community/Eduhub-Community.github.io#159]
I would like to work on improving the index.html making it engaging for the users and make it more expressive. I would like to add features in it and make it more expressive.

**Comment by harshsingh32** [comment]
I would like to work on this issue,  please assign this issue to me under GSSoC'23.

**Comment by VC6378** [comment]
I have good hold on HTML, I can make it really optimized. Please assign me this issue.
