### ISSUE TITLE
Improve the navbar in the E learning section

### ISSUE THREAD

**Issue by karthiknadar1204** [Eduhub-Community/Eduhub-Community.github.io#168]
We should add the dark-light mode button to the top on the navbar and imprve the spacing on the navbar to make it look more alluring and engaging

**Comment by karthiknadar1204** [comment]
I would like to work on this issue under gssoc'23

**Comment by sagarb2003** [comment]
Hey
I want to add some more design to the navbar in E-learning Section.
And can also do more specifications.
Please assign me this task under GSSoc'23
