### ISSUE TITLE
Fix Button Border

### ISSUE THREAD

**Issue by MOHDNEHALKHAN** [Eduhub-Community/Eduhub-Community.github.io#170]
The button border is not looking good, it has to be removed from the button
![Screenshot 2023-05-20 182109](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/125626654/4852400c-3c0d-4151-93fb-eae77cab6bc2)
![Screenshot 2023-05-20 181900](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/125626654/8457f8a1-9703-431b-a600-eee48d0323cc)

@SahityaRoy Please assign me this issue

**Comment by MOHDNEHALKHAN** [comment]
As a gssoc'2023 contributor, I want to work on this issue

**Comment by DhairyaMajmudar** [comment]
please assign this issue to me I will contribute to this issue under GSSoC'23. I will fix the border issue by adding the necessary code for the border.
