### ISSUE TITLE
Remove comment closing tag 

### ISSUE THREAD

**Issue by devWonderkind** [Eduhub-Community/Eduhub-Community.github.io#210]
![eduhub](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/110322061/af44acae-fd81-4a62-b02e-c1f62d0562b0)
 
@SahityaRoy Please assign this issue to me under GSSoC'23.

**Comment by yash8917** [comment]
I would like to work on this issue pls assign me under the GSSOC '2023
