### ISSUE TITLE
[GSSoC '23] Some fixes which would make the website even more beautiful

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Eduhub-Community/Eduhub-Community.github.io#223]
1. Properly align the images, they are completely left aligned
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/133862694/9f16e02c-af92-4b3e-9bfe-9e967f066700)
2.The Join us and other buttons have some outer border which doesn't go with the website's theme. I'd like to change that
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/133862694/d844c841-69f9-4254-b933-564540975c85)
3.  Change the size of the footer and properly orient the objects
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/133862694/07d66f32-0419-4feb-afc2-d13117f34a6c)

**Comment by PoulavBhowmick03** [comment]
Check these issue if they can be assigned @SahityaRoy

**Comment by SahityaRoy** [comment]
> Check these issue if they can be assigned @SahityaRoy

Please go ahead with this and enhance the UI.
