### ISSUE TITLE
Toggle button in FAQ section is working in one way

### ISSUE THREAD

**Issue by sumitkr2000** [Eduhub-Community/Eduhub-Community.github.io#265]
Hey, the toggle button in the faq section should work both ways but it is working only one way. I want to fix this bug. Please assign me this issue. Thank you!

**Comment by 007AnupamSharma** [comment]
please assign me this issue .. i'll do according to your suggestion gssoc23

**Comment by sumitkr2000** [comment]
Please assign me this issue so that I can start working on it.
