### ISSUE TITLE
Missing PR template

### ISSUE THREAD

**Issue by Anshika-Jain02** [Eduhub-Community/Eduhub-Community.github.io#280]
*Addition of Pull Request Template to improve clarity and to make it easier for new contributors.*

**Please assign this issue to me under GSSoC'23 @SahityaRoy**

**Comment by SahityaRoy** [comment]
Yup go ahead

**Comment by SahityaRoy** [comment]
what is the update

**Comment by Anshika-Jain02** [comment]
@SahityaRoy Sir, i will complete it by tomorrow. Sorry for the delay. My exams are going on right now.
