### ISSUE TITLE
To incerease size of icons 

### ISSUE THREAD

**Issue by DhairyaMajmudar** [Eduhub-Community/Eduhub-Community.github.io#285]
The size of the icons of companies in the last row of the collaborators' section is not appropriate as compared to others. It must be fixed

**Comment by DhairyaMajmudar** [comment]
Please assign this issue to me under GSSoC'23. I will improve the size of icons with the help of HTML, and CSS.

**Comment by Snigdha2712** [comment]
Please assign this project to me. I will fix the issue

**Comment by DhairyaMajmudar** [comment]
Thank You @SahityaRoy  for assigning me this issue
