### ISSUE TITLE
Display the list of people who made the contribution 

### ISSUE THREAD

**Issue by Anamika-Ratna** [Eduhub-Community/Eduhub-Community.github.io#292]
Hello , I would like to add a section where names of the contributers will be displayed on your website page .

Therefore I request you to kindly assign me this task under the tag GSSoC- 23

**Comment by abhi03ruchi** [comment]
I would like to work on this issue, plz assign it to me.

**Comment by Anamika-Ratna** [comment]
Hi @SahityaRoy kindly review the changes 
Here is the contributor section mentioned at top 
![Screenshot (388)](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/122286548/8a5a14dd-ddb1-4fdd-b252-4e159f2c4005)

The page looks like this . 

![Screenshot (389)](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/122286548/3960aa6d-a706-4aa1-9854-8a5345ce9ac4)
