### ISSUE TITLE
In the team section of homepage, the text on hover is not visible [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [Eduhub-Community/Eduhub-Community.github.io#305]
In the homepage, in the Team section, the text on hover is not visible. 
![isseum1](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/da05229c-0efb-47fa-8088-c20f24a8957f)

Please assign me this issue.

**Comment by 1Shubham7** [comment]
Please assign me this issue.

**Comment by SahityaRoy** [comment]
also can you please fix the bellow button

**Comment by 1Shubham7** [comment]
Yes @SahityaRoy . I would love to. Please assign me this issue.

**Comment by 1Shubham7** [comment]
Thank you @SahityaRoy .
