### ISSUE TITLE
E-Learning (Dark mode) text not visible/Readable [GSSoC'23]

### ISSUE THREAD

**Issue by 1Shubham7** [Eduhub-Community/Eduhub-Community.github.io#309]
The text in E-Learning page of the website is not visible in the dark mode. It is unreadable

![notvisible3](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/f65430f3-0792-408f-a005-c06fa73a88d1)
![notvisible1](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/144ca921-7ed2-4a0d-a092-b0184a78f701)
![notvisible](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/116020663/a1558fea-a2ff-404b-9a29-ee9d7d081006)

Please assign me this issue under GSSoC'23

**Comment by Kapileswar-Moharana** [comment]
I have already worked on this type of issue like enhancing the dark mode by adjusting the content color according to the mode in a project which was assigned to me https://github.com/CatsInTech/GitHub-ReadMe/issues/5 , Assign me this issue under GSSoC'23.I will manage the colour according to the dark mode and light mode itself.
