### ISSUE TITLE
Styling Event Cards

### ISSUE THREAD

**Issue by Swapnil-Singh-99** [Eduhub-Community/Eduhub-Community.github.io#325]
## Issue 
I will be styling event cards using css

## Screenshots

![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/85278243/ae00a9fa-5256-4818-aa49-07bd84e05b4c)

Please assign me this task under GSSOC'23

**Comment by SahityaRoy** [comment]
Please go ahead and style the cards

**Comment by Swapnil-Singh-99** [comment]
👍
