### ISSUE TITLE
Use Lazy loading

### ISSUE THREAD

**Issue by sumitkr2000** [Eduhub-Community/Eduhub-Community.github.io#332]
### Is your feature request related to a problem? Please describe.

I want to implement lazy loading on the website. Without lazy loading the website is taking so much time to load the whole content. Please assign me this issue. Thank you!

### Describe the solution you'd like

Use lazy loading to render the sections only when user scrolls to that section.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshAman999** [comment]
seems like a nice addition ✔️
