### ISSUE TITLE
college name section in contact form

### ISSUE THREAD

**Issue by Sushilverma002** [Eduhub-Community/Eduhub-Community.github.io#338]
### Is your feature request related to a problem? Please describe.

it would be better have college name in the contact form.
you will know more accurate information about it.
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/114687502/797bb21f-e2bd-4333-85cd-a20ef6b7a73f)

### Describe the solution you'd like

solution:- the college section added just below name.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by silky-modi22** [comment]
I want to work on this issue under GSSOC 2023 please assign me

**Comment by sagarb2003** [comment]
I want to make contact us form more interactive
Please assign me this issue under GSSOC'23
