### ISSUE TITLE
[GSSoC'23]:want to add Dark mode

### ISSUE THREAD

**Issue by Yashoda2003** [Eduhub-Community/Eduhub-Community.github.io#342]
### Is your feature request related to a problem? Please describe.

 Lack of dark mode.

### Describe the solution you'd like

I want to add dark mode to website.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Dimple-01** [comment]
I want to work on this issue.
Please assign this work to me.

**Comment by MohammadBinAftab** [comment]
please assign me this issue. I will use HTML, CSS and JS to get it right.

**Comment by Kapileswar-Moharana** [comment]
I have already worked on React project in which I have to enhance the Dark mode in Home Section as well as in the Docs Section you can check https://github.com/CatsInTech/GitHub-ReadMe  , Task was assigned to me under Enhance the Dark Mode, So Assign me this issue Under GSSoC'23. I will enhance the Dark mode By using Js or React to work better.
