### ISSUE TITLE
[FEATURE]: Add Google Maps in Contact Section 

### ISSUE THREAD

**Issue by trishanu-init** [Eduhub-Community/Eduhub-Community.github.io#358]
### Is your feature request related to a problem? Please describe.

The current version of the site only has the address for the HQ written in plain text , i think it will look more attractive and User friendly if we include google maps alongside the contact form

### Describe the solution you'd like

Something Like this 👇

![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/85580785/e2253820-f235-4c88-a52c-ae31570de6cd)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by gitsofaryan** [comment]
@trishanu-init I wanted to work on this issue!

**Comment by trishanu-init** [comment]
@AshAman999 please review and assign this issue
