### ISSUE TITLE
This community need a Gallery section photo gallery 

### ISSUE THREAD

**Issue by SahityaRoy** [Eduhub-Community/Eduhub-Community.github.io#36]

**Comment by SahityaRoy** [comment]
![08 10 2022_14 43 31_REC](https://user-images.githubusercontent.com/72821604/194699945-b094d97a-654b-45d3-be45-f0a053a5afc5.png)

**Comment by Ishnoor-kaur** [comment]
i can help out in this

**Comment by its-me-Harsh-Anand** [comment]
Hey @SahityaRoy , I want to work on this issue. Please assign me.

If assigned, do I have to enhance this page [➡️ https://eduhubcommunity.tech/gallery.html](https://eduhubcommunity.tech/gallery.html)

**Comment by thedevildude** [comment]
Hey @SahityaRoy I have been working on the issue for some time. Can you please assign me.

**Comment by shrutimeg** [comment]
@SahityaRoy I want to work on these issue please  assign me this issue .
