### ISSUE TITLE
Add more Frequently asked questions

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Eduhub-Community/Eduhub-Community.github.io#370]
### Is your feature request related to a problem? Please describe.

There are only 3 faqs available. Users 1st time to the website need more info an might have more questios

### Describe the solution you'd like

Add questions like
Are there any prerequisites or requirements to become a member?
How can I participate in peer-to-peer learning sessions?
Can I connect with other community members outside of the learning sessions?
Are there any certification programs or recognition for active community members?

### Describe alternatives you've considered

You can suggest what to add among these, or I can add all of these for the user to have more context towards this project

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Viveksati5143** [comment]
Please assign me this issue under GSSOC'23.

**Comment by AshAman999** [comment]
Hey @PoulavBhowmick03 , will you be working on this one?

**Comment by Viveksati5143** [comment]
I don't think so coz he already have many opened issues any working on them but this is my first contribution to your repo.

**Comment by PoulavBhowmick03** [comment]
> Hey @PoulavBhowmick03 , will you be working on this one?

Yes

**Comment by PoulavBhowmick03** [comment]
@SahityaRoy Please assign this to me
