### ISSUE TITLE
Add more courses in the E-School

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Eduhub-Community/Eduhub-Community.github.io#371]
### Is your feature request related to a problem? Please describe.

There are currently no courses mentioned for MongoDB, MySQL, Node JS, HTTPs Networking

### Describe the solution you'd like

I want to add sections for MongoDB, MySQL, Node JS, HTTPs Networking courses and link it to respective Youtube videos
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/133862694/0354c9b1-ccf3-454e-98d5-4986b169c616)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by PoulavBhowmick03** [comment]
@SahityaRoy Please assign this to me

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.

**Comment by PoulavBhowmick03** [comment]
@SahityaRoy Can you look into this issue, and assign it
