### ISSUE TITLE
Improve the Navbar elements and their orientation in E-School websiite

### ISSUE THREAD

**Issue by PoulavBhowmick03** [Eduhub-Community/Eduhub-Community.github.io#372]
### Is your feature request related to a problem? Please describe.

The navbar and its elements look disaligned and unorganised. 
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/133862694/dbf619a7-7a2f-4cfc-b9e9-eaf363da8bfc)

### Describe the solution you'd like

Make them organised, add padding and improve the navbar

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChavvaNarayana** [comment]
Please assign to me this issue.

**Comment by PoulavBhowmick03** [comment]
@SahityaRoy Please assign this to me
