### ISSUE TITLE
 Fix Bug event page

### ISSUE THREAD

**Issue by Spyder15** [Eduhub-Community/Eduhub-Community.github.io#39]
Fix Bug event page, Responsive page

**Comment by ashutosh7i** [comment]
can i do this? please assign it to me

**Comment by ashutosh7i** [comment]
can i do this? please assign it to me

**Comment by Spyder15** [comment]
@ashutosh7i u can proceed with this issue

**Comment by ashutosh7i** [comment]
i dont see any bug in the page, please specify or i merge optimized code

**Comment by shrutimeg** [comment]
I want to solve these issue

**Comment by Spyder15** [comment]
@shrutimeg you can proceed with this issue

**Comment by Athi223** [comment]
I'd like to contribute to this, if its still available

**Comment by Spyder15** [comment]
@Athi223 u can proceed
