### ISSUE TITLE
[Enhancement] Event cards are not centered on small screen

### ISSUE THREAD

**Issue by ritik48** [Eduhub-Community/Eduhub-Community.github.io#394]
#### Problem
On small screen the event cards are not centered therefore lots of space are left and it doesn't look good.

![eduhub center events](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/84488726/94087ec3-cca6-4a36-93f4-4b7510ae0820)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by ChavvaNarayana** [comment]
Sounds good to me. I'm willing to contribute.
