### ISSUE TITLE
nav bar not proper visible in mobile view

### ISSUE THREAD

**Issue by devWonderkind** [Eduhub-Community/Eduhub-Community.github.io#402]
### Is your feature request related to a problem? Please describe.

@SahityaRoy navigation bar is not visible properly and needs improvement in styling.
here you can see:
![mobileview](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/110322061/3c5ff1e5-ca46-4007-a000-4698443cb38d)

### Describe the solution you'd like

I wanna change navigation styling like text color and background color. After this change, it may look good.

### Additional context

Please assign this task to me under GSSoC'23.

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by SahityaRoy** [comment]
Please start working
