### ISSUE TITLE
Implement Dark Mode

### ISSUE THREAD

**Issue by neha030** [Eduhub-Community/Eduhub-Community.github.io#46]
Add a new feature to change from light mode to dark mode.

**Comment by nalin-programmer** [comment]
Assign this to me

**Comment by neha030** [comment]
> Assign this to me

Go Ahead !!

**Comment by shrutimeg** [comment]
@neha030 I want to solve these issue

**Comment by Priya69149** [comment]
I want to solve these issue

**Comment by Priya69149** [comment]
@neha030 I want to solve these issue
