### ISSUE TITLE
fix: button doesn't function properly

### ISSUE THREAD

**Issue by Viveksati5143** [Eduhub-Community/Eduhub-Community.github.io#467]
### Describe the bug

The arrow button in the team section only works on clicking the arrow in the button (which is on a minute area)

### Expected behaviour

The button should work on clicking anywhere on the button.

### Screenshots

<img width="960" alt="image" src="https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/100852245/6362ed11-9a38-48f2-adeb-d3dfbfb38d90">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by arihantJ24** [comment]
can u assign this issuen to mee

**Comment by AshAman999** [comment]
Will you work on this @Viveksati5143 ?

**Comment by Viveksati5143** [comment]
> Will you work on this @Viveksati5143 ?

Yes!

**Comment by Viveksati5143** [comment]
> Will you work on this @Viveksati5143 ?

Assign it to me
