### ISSUE TITLE
Adding dark mode to Gallery section of the website

### ISSUE THREAD

**Issue by Viveksati5143** [Eduhub-Community/Eduhub-Community.github.io#474]
### Is your feature request related to a problem? Please describe.

Gallery section don't have dark mode available for the users as visible in the screenshot.

### Describe the solution you'd like

I will integrate dark mode to gallery section as well for the comfort of users!!

### Additional context

<img width="960" alt="image" src="https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/100852245/96a45f3f-f41e-4636-9efb-c4bd9475f67c">

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Viveksati5143** [comment]
@SahityaRoy I want to work in this issue under GSSOC'23

**Comment by jyoti145** [comment]
Hey I want to work on this issue please assign me

**Comment by Viveksati5143** [comment]
@AshAman999 I want to work in this issue under gssoc

**Comment by AshAman999** [comment]
> Hey I want to work on this issue please assign me

If you wanna work on other issues , please feel free to create one or ask anyone to assign u one
