### ISSUE TITLE
unnecessary space in footer and the text alignment is broken 

### ISSUE THREAD

**Issue by Sushilverma002** [Eduhub-Community/Eduhub-Community.github.io#491]
### Describe the bug

the unnecessary space left on last footer and the text in footer is not properly aligned.

### Expected behaviour

there should be no space and text must be properly aligned 

### Screenshots

![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/114687502/e5b8d917-a9ad-4698-8f97-2bf95b9eb941)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Viveksati5143** [comment]
> ### Describe the bug
> the unnecessary space left on last footer and the text in footer is not properly aligned.
> 
> ### Expected behaviour
> there should be no space and text must be properly aligned
> 
> ### Screenshots
> ![image](https://user-images.githubusercontent.com/114687502/252147499-e5b8d917-a9ad-4698-8f97-2bf95b9eb941.png)
> 
> ### Additional context
> _No response_
> 
> ### Code of Conduct
> * [x]  I agree to follow this project's Code of Conduct

Is this of events page?
If yes, then I already have a pr pending for review of the same 
Refer #466

**Comment by Sushilverma002** [comment]
not for event page this one for gallery section. @Viveksati5143
