### ISSUE TITLE
Contact form not working

### ISSUE THREAD

**Issue by PhilsKay** [Eduhub-Community/Eduhub-Community.github.io#51]
![contact-error](https://user-images.githubusercontent.com/86670745/194772719-03b9ad5a-fcf5-4535-a03f-f14257bb6057.png)

**Comment by PhilsKay** [comment]
@SahityaRoy Pls assign I can help solve the issue

**Comment by SahityaRoy** [comment]
@PhilsKay please go ahead

**Comment by PhilsKay** [comment]
Ok thanks

**Comment by SahityaRoy** [comment]
Solved
