### ISSUE TITLE
I will Re-create the Footer section in Events page [GSsoc'23]

### ISSUE THREAD

**Issue by Monilprajapati** [Eduhub-Community/Eduhub-Community.github.io#542]
### Is your feature request related to a problem? Please describe.

Whenever we click on Explore more events button it opens new page called eventPage.html where the footer section is not in perfect position and do not have proper CSS.

I will redesign it and will put it at perfect position.

### Describe the solution you'd like

I will crate the user friendly footer which is reliable to your website!!

Footer right now :: -
![image](https://github.com/Eduhub-Community/Eduhub-Community.github.io/assets/99136041/d5f05ffb-49c1-4941-b600-87d8600f5356)

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by AshitaBidkar** [comment]
I want to work on this issue, kindly assign it to me.

**Comment by g-sandeep-reddy** [comment]
I will redesign it and will put it at perfect position.
