### ISSUE TITLE
Enhancement on e-learning page

### ISSUE THREAD

**Issue by manika137** [Eduhub-Community/Eduhub-Community.github.io#80]
I would like to enhance the e-learning page by
- Improving the navbar
- Changing the fonts since the text isn't visible
<img width="945" alt="image" src="https://user-images.githubusercontent.com/80244229/195980029-e497aec9-5731-4b99-9e73-94103097df90.png">
<img width="947" alt="image" src="https://user-images.githubusercontent.com/80244229/195980041-52d2b1e0-e158-4b57-a22e-b95f130a8d06.png">
<img width="948" alt="image" src="https://user-images.githubusercontent.com/80244229/195980050-c2a3b94d-09d2-43ce-9925-76b54ff129f9.png">

@Spyder15 @SahityaRoy, please assign me this issue

**Comment by Spyder15** [comment]
@manika137 you can go ahead
